# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: pr

on: pull_request

jobs:

  test:
    name: test
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout Repository
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

    - name: Use Node.JS 22.x
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
      with:
        node-version: 22.x

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test
