# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: pr

on: pull_request

jobs:

  test:
    name: test
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout Repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    - name: Use Node.JS 16.x
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test
